version: '3.8'
services:
  app:
    container_name: sport-plus
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    environment:
      SPRING_APPLICATION_JSON: '{"postgres.jdbcUrl": "jdbc:postgresql://dbpostgresql:5432/postgres"}'
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres