version: '3.8'
services:
  app:
    container_name: sport-plus
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    environment:
      SPRING_APPLICATION_JSON: '{
                                  "postgres.jdbcUrl": "jdbc:postgresql://dbpostgresql:5432/${PG_DATABASE}",
                                  "postgres.username": "${PG_USER}",
                                  "postgres.password": "${PG_PASSWORD}"
                                }'
  dbpostgresql:
    image: postgres
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
